//! Isolation contract — layer-1 physical isolation for multi-agent work.
//!
//! One agent works in one git worktree on one branch. Two agents therefore
//! cannot overwrite each other's files: their working trees are disjoint and
//! their writes land on separate branches. Conflicts surface at merge time,
//! never silently mid-edit.
//!
//! This contract is the DESCRIBED intention, not the executed action. The forge
//! engine validates it and produces a deterministic merge plan; the host agent
//! (DC9 — scale-with-the-model) is the one that runs `git worktree add` /
//! `git rebase`. Forge never shells out (keeps the engine pure, deterministic,
//! and free of a git-subprocess coupling).
//!
//! See `crates/forge-core-engine/src/isolation.rs` for the pure logic.

use crate::common::{RepoPath, StableId};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Top-level YAML document wrapping an isolation contract (mirrors the
/// `XDocument` shape used by every other forge contract).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct IsolationContractDocument {
    pub schema_version: String,
    pub isolation_contract: IsolationContract,
}

/// A single agent's physical isolation record.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct IsolationContract {
    /// Unique isolation id (e.g. `iso-alice-s5.0-a1b2`). Generated by the CLI,
    /// never by the pure engine (determinism).
    pub id: StableId,
    /// The agent this worktree belongs to. Must match the linked claim's
    /// claimant when `claim_id` is set (DD36).
    pub agent_id: StableId,
    /// Git branch name, conventionally `<agent>/<scope>` (DD32). Validated for
    /// git-ref legality (no `..`, whitespace, `:`, leading `-`/`.`).
    pub branch_name: String,
    /// Working-tree path, relative to the repo root (DD33). Conventionally
    /// `../.forge-worktrees/<agent>/<suffix>`. Must be unique across contracts.
    pub worktree_path: RepoPath,
    /// The ref (branch or commit sha) the worktree branched from. Free-form —
    /// the engine does not resolve refs (DD31 — no git subprocess).
    pub base_ref: String,
    /// RFC3339 timestamp the isolation was proposed/created.
    pub created_at: String,
    /// Lifecycle state (DD35).
    pub status: IsolationStatus,
    /// How this isolation should be merged back (DD34).
    pub merge_policy: MergePolicy,
    /// Optional link to the semantic claim this isolation serves (DD36). When
    /// present, the engine cross-checks that the claim belongs to `agent_id`.
    pub claim_id: Option<StableId>,
}

/// Lifecycle of an isolation contract (DD35). Terminal states are `Merged` and
/// `Abandoned`; everything else is recoverable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum IsolationStatus {
    /// Proposed but the worktree is not yet confirmed created.
    Proposed,
    /// Worktree exists; agent is actively writing on `branch_name`.
    Active,
    /// Agent has signalled done; merge-back is in progress.
    Merging,
    /// Merge landed on the base ref; worktree may be removed. Terminal.
    Merged,
    /// Agent abandoned without merging; worktree may be removed. Terminal.
    Abandoned,
}

/// Merge strategy the merge plan is built around (DD34).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum MergePolicy {
    /// Rebase the branch onto the current base ref, then fast-forward. Keeps
    /// history linear. The default.
    #[default]
    Rebase,
    /// Create a merge commit. Preserves branch topology.
    Merge,
    /// Squash all branch commits into one on the base ref.
    Squash,
}

/// A fully-resolved merge plan: an ordered, deterministic sequence of git steps
/// the host agent executes. The engine emits this; it never runs it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct MergePlan {
    /// The isolation this plan merges.
    pub isolation_id: StableId,
    /// The agent whose work is being merged.
    pub agent_id: StableId,
    /// Branch being merged.
    pub branch_name: String,
    /// Target ref the work lands on.
    pub base_ref: String,
    /// Strategy used to build the steps.
    pub policy: MergePolicy,
    /// Ordered steps. Execute in order; stop on the first non-zero git exit.
    pub steps: Vec<MergeStep>,
}

/// One step of a merge plan. `args` are the literal argv after the git
/// subcommand (e.g. `["worktree", "remove", "../.forge-worktrees/alice/s5.0"]`).
/// `rationale` explains WHY this step exists, for the agent's log.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct MergeStep {
    /// The git subcommand family this step belongs to.
    pub action: GitAction,
    /// Literal argv after the git subcommand. Intended to be passed to git as
    /// `git <args...>`.
    pub args: Vec<String>,
    /// Human/agent-readable reason for this step.
    pub rationale: String,
}

/// The git subcommand families a merge plan uses. Deliberately narrow — only
/// what isolation lifecycle needs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub enum GitAction {
    /// `git worktree add <path> <branch>`
    WorktreeAdd,
    /// `git worktree remove <path>`
    WorktreeRemove,
    /// `git checkout <ref>` / `git switch`
    Checkout,
    /// `git fetch` / `git pull` to refresh the base ref.
    Fetch,
    /// `git rebase <base> <branch>`
    Rebase,
    /// `git merge --no-ff <branch>`
    Merge,
    /// `git merge --squash <branch>` + commit
    Squash,
    /// `git branch -d <branch>` cleanup
    BranchDelete,
}

/// Engine-level rejection of an isolation contract or transition.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum IsolationError {
    /// Branch name is not a legal git ref (DD32).
    IllegalBranchName { branch_name: String, reason: String },
    /// Worktree path is empty / absolute-traversal / reserved.
    IllegalWorktreePath {
        worktree_path: String,
        reason: String,
    },
    /// Two contracts claim the same branch (DD32 uniqueness).
    DuplicateBranch {
        branch_name: String,
        owner: StableId,
    },
    /// Two contracts claim the same worktree path (DD33 uniqueness).
    DuplicateWorktreePath {
        worktree_path: String,
        owner: StableId,
    },
    /// claim_id set but the claim does not belong to this agent (DD36).
    ClaimAgentMismatch {
        claim_id: StableId,
        expected: StableId,
        actual: StableId,
    },
    /// created_at is not parseable RFC3339.
    UnparseableCreatedAt { raw: String },
    /// base_ref is empty.
    EmptyBaseRef,
    /// A field that flows into a copy-pasted shell command contains a shell
    /// metacharacter (review S4.6 C1 defense-in-depth). `field` is the
    /// contract field name; `value` is the offending input.
    ShellMetacharInField { field: String, value: String },
    /// agent_id is empty.
    EmptyAgentId,
    /// Illegal lifecycle transition (DD35).
    IllegalTransition {
        from: IsolationStatus,
        to: IsolationStatus,
    },
}

impl std::fmt::Display for IsolationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            IsolationError::IllegalBranchName {
                branch_name,
                reason,
            } => write!(f, "illegal branch name '{branch_name}': {reason}",),
            IsolationError::IllegalWorktreePath {
                worktree_path,
                reason,
            } => write!(f, "illegal worktree path '{worktree_path}': {reason}",),
            IsolationError::DuplicateBranch { branch_name, owner } => write!(
                f,
                "branch '{branch_name}' already held by agent '{}'",
                owner.0,
            ),
            IsolationError::DuplicateWorktreePath {
                worktree_path,
                owner,
            } => write!(
                f,
                "worktree path '{worktree_path}' already held by agent '{}'",
                owner.0,
            ),
            IsolationError::ClaimAgentMismatch {
                claim_id,
                expected,
                actual,
            } => write!(
                f,
                "claim '{}' belongs to agent '{}', not '{}'",
                claim_id.0, expected.0, actual.0,
            ),
            IsolationError::UnparseableCreatedAt { raw } => {
                write!(f, "created_at '{raw}' is not valid RFC3339")
            }
            IsolationError::EmptyBaseRef => write!(f, "base_ref is empty"),
            IsolationError::ShellMetacharInField { field, value } => write!(
                f,
                "field '{field}' contains a shell metacharacter: {value:?}",
            ),
            IsolationError::EmptyAgentId => write!(f, "agent_id is empty"),
            IsolationError::IllegalTransition { from, to } => {
                write!(
                    f,
                    "illegal transition {} -> {}",
                    status_lc(*from),
                    status_lc(*to),
                )
            }
        }
    }
}

/// Lowercase snake_case name for an [`IsolationStatus`] (mirrors the serde
/// `rename_all = "snake_case"`), for use in human-readable messages.
fn status_lc(s: IsolationStatus) -> &'static str {
    use IsolationStatus::*;
    match s {
        Proposed => "proposed",
        Active => "active",
        Merging => "merging",
        Merged => "merged",
        Abandoned => "abandoned",
    }
}
