//! `forge-core-research` — the Policy Enforcement Point (PEP) for the F14
//! research source trust model (ADR-0010).
//!
//! Candidato 1 (in `forge-core-contracts`) built the pure decision function
//! [`forge_core_contracts::ResearchContract::can_admit_source`]. This crate is its enforcement
//! counterpart: it calls that PDP and appends a `SourceAdded` event
//! **atomically** under an exclusive file lock, closing the TOCTOU window
//! between decide and write (CWE-367 — atomicity at the write site; ADR-0010).
//!
//! # Architecture (mirrors ADR-0024 / `forge-core-memory`)
//!
//! - **Event log** (`research/sources.ndjson`): append-only JSONL. The source
//!   of truth. Never mutated in place ("the dataset only grows").
//! - **Projection** ([`ResearchProjection`]): the rebuildable read model
//!   (`source_id → current source`, `superseded` set), rebuilt by replaying
//!   the log (Fowler event-sourcing: discard and rebuild the projection).
//! - **Lock**: `fs4` exclusive OS file lock via
//!   `forge_core_store::acquire_effect_store_lock`, held across decide-and-write.
//!   Reused verbatim — the store crate already implements TOCTOU-safe locking.
//!
//! The PEP **never re-evaluates policy** (Cedar/OPA/XACML): a denied decision
//! is a `DeniedByGate` outcome, not an error, and appends nothing.
//!
//! # Why a separate log from memory (ADR-0010 rationale)
//!
//! Reusing the memory log (treating `ResearchSource` as a `MemoryEvent` kind)
//! would fuse two trust domains — *authority/review* (F06: "is this
//! ground-truth actionable?") and *citation provenance* (F14: "does this
//! point to a registered source?") — in a single event-sourced log. That is
//! the Model B class of bug one layer down. F14 keeps its own log, lock, and
//! projection; the two subsystems share only the `SourceId` namespace at the
//! citation-check boundary (which lives in `forge-core-validate`).

pub mod admission;
pub mod error;
pub mod graph;

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use forge_core_contracts::ResearchSource;
use forge_core_eventlog::{event_envelope, EventSourced};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

// Re-export the generic event-log mechanics under the research crate's public
// paths so the public API stays stable. These are the generic versions
// parameterised over [`ResearchDomain`]'s [`EventSourced`] impl: callers pass
// owned events to `replay`, and `project_locked` takes `(root, log_rel_path)`.
pub use forge_core_eventlog::{next_sequence, now_unix, project_locked, replay};

pub use admission::{admit_source, admit_source_with_durability, AdmissionResult, AdmissionStatus};
pub use error::{ResearchAdmitError, ResearchProjectionError};
pub use graph::{evidence_graph, ClaimRef};

/// State-root-relative path of the append-only research source event log.
pub const RESEARCH_LOG_RELATIVE_PATH: &str = "research/sources.ndjson";

/// State-root-relative path of the exclusive lock guarding the research log.
/// Held across every decide-and-write critical section (CWE-367).
pub const RESEARCH_LOCK_RELATIVE_PATH: &str = "locks/research.sources.lock";

/// The append-only event stream that is the source of truth for the research
/// Source Ledger. One JSON object per line in `research/sources.ndjson`. Never
/// mutated in place; the projection ([`ResearchProjection`]) is the disposable
/// read model.
///
/// Variants mirror the PEP operations:
/// - [`SourceAdded`](ResearchEvent::SourceAdded) — a source entered the ledger,
///   gated by `ResearchContract::can_admit_source`.
/// - [`SourceRetired`](ResearchEvent::SourceRetired) — explicit removal. Carries
///   the FULL before-image (Debezium `before` / Postgres `REPLICA IDENTITY
///   FULL`), making the log reversible-by-replay (mirrors `MemoryEvent::Forgotten`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub enum ResearchEvent {
    SourceAdded {
        sequence: u64,
        at_unix: u64,
        source: ResearchSource,
    },
    SourceRetired {
        sequence: u64,
        at_unix: u64,
        /// Full prior source — the audit before-image. Replaying the log
        /// without this event restores the source.
        before: ResearchSource,
    },
}

// The `sequence()`/`at_unix()` envelope accessors + `EventEnvelope` impl are
// generated by the `event_envelope!` macro from forge-core-eventlog (the most
// mechanical triplication — every variant carries `sequence`/`at_unix`).
event_envelope!(ResearchEvent, [SourceAdded, SourceRetired]);

/// Severity for a projection diagnostic. Mirrors the memory PEP's
/// `MemoryProjectionSeverity` granularity (error/warning) without importing
/// the validator crate — this crate stays decoupled.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ResearchProjectionSeverity {
    Warning,
    Error,
}

/// A non-fatal observation produced while replaying the log (e.g. a torn final
/// line was skipped, or an out-of-order sequence was seen). The projection
/// stops at the last valid record rather than erroring, mirroring the memory
/// PEP's `RecoveryStopped` as a diagnostic, not a hard fail.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ResearchProjectionDiagnostic {
    pub severity: ResearchProjectionSeverity,
    /// Stable diagnostic code (e.g. `"torn_final_line_skipped"`).
    pub code: String,
    pub message: String,
}

/// The rebuildable read model: `source_id → current source` plus the
/// `superseded` set (retired ids). Rebuilt from scratch by [`replay`]; never
/// the source of truth (the event log is). Last-event-wins per `source_id`,
/// matching the memory PEP's discipline.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ResearchProjection {
    /// The highest sequence number applied so far. The next event written is
    /// `sequence + 1`.
    pub sequence: u64,
    /// `source_id.0 → current ResearchSource`. Inserted by `SourceAdded`;
    /// removed by `SourceRetired`.
    pub sources: BTreeMap<String, ResearchSource>,
    /// `source_id.0` values that have been retired. Membership prevents a
    /// stale writer from re-resurrecting a retired id (defence-in-depth).
    pub superseded: BTreeSet<String>,
    /// Non-fatal observations from the last replay.
    pub diagnostics: Vec<ResearchProjectionDiagnostic>,
}

impl ResearchProjection {
    /// Apply a single event, advancing the projection. Thin wrapper that
    /// delegates to the generic [`forge_core_eventlog::apply_event`] (which owns
    /// the out-of-order guard); the domain fold itself lives in
    /// [`ResearchDomain`]'s [`EventSourced::apply`] impl. Kept as a method so
    /// existing callers/tests that hold a `&mut ResearchProjection` keep working.
    pub fn apply_event(&mut self, event: &ResearchEvent) {
        forge_core_eventlog::apply_event::<ResearchDomain>(self, event);
    }

    /// Number of live (non-retired) sources.
    #[must_use]
    pub fn len(&self) -> usize {
        self.sources.len()
    }

    /// Whether there are no live sources.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.sources.is_empty()
    }
}

/// The marker type carrying the research domain's [`EventSourced`] impl. The
/// generic event-log mechanics (`replay`, `project_locked`, `append_event`,
/// `next_sequence`) are parameterised over this type so they resolve to the
/// research event/projection/diagnostic types.
pub struct ResearchDomain;

impl EventSourced for ResearchDomain {
    type Event = ResearchEvent;
    type Projection = ResearchProjection;
    type Diagnostic = ResearchProjectionDiagnostic;

    fn apply(projection: &mut Self::Projection, event: &Self::Event) {
        match event {
            ResearchEvent::SourceAdded { source, .. } => {
                let key = source.id.0.clone();
                projection.sources.insert(key, source.clone());
            }
            ResearchEvent::SourceRetired { before, .. } => {
                let key = before.id.0.clone();
                projection.sources.remove(&key);
                projection.superseded.insert(key);
            }
        }
    }

    fn record_diagnostic(projection: &mut Self::Projection, diagnostic: Self::Diagnostic) {
        projection.diagnostics.push(diagnostic);
    }

    fn sequence_of(projection: &Self::Projection) -> u64 {
        projection.sequence
    }

    fn advance_sequence(projection: &mut Self::Projection, new_sequence: u64) {
        projection.sequence = new_sequence;
    }

    fn diagnostic_out_of_order_event_ignored(
        event_seq: u64,
        projection_seq: u64,
    ) -> Self::Diagnostic {
        ResearchProjectionDiagnostic {
            severity: ResearchProjectionSeverity::Warning,
            code: forge_core_eventlog::CODE_OUT_OF_ORDER_EVENT_IGNORED.into(),
            message: format!(
                "event sequence {event_seq} <= projection sequence {projection_seq}; ignored"
            ),
        }
    }

    fn diagnostic_torn_final_line_skipped(
        line_number: usize,
        source: &serde_json::Error,
    ) -> Self::Diagnostic {
        ResearchProjectionDiagnostic {
            severity: ResearchProjectionSeverity::Warning,
            code: forge_core_eventlog::CODE_TORN_FINAL_LINE_SKIPPED.into(),
            message: format!("skipped incomplete final line {line_number}: {source}"),
        }
    }
}

/// The status of an [`project`] read. The `Ok` arm always carries the
/// projection (which may itself carry diagnostics); only structural I/O or
/// deserialization failures are `Err`. Now an alias for
/// [`EventLogError<ResearchProjectionDiagnostic>`](forge_core_eventlog::EventLogError).
pub type ProjectionResult = Result<ResearchProjection, ResearchProjectionError>;

/// Read the research log under the lock and rebuild the projection by replay.
///
/// **Acquires the lock.** Callers already holding the research lock (the PEP
/// entry point: `admit_source`) must call [`forge_core_eventlog::project_locked`]
/// instead — fs4 locks are NOT re-entrant, so re-acquiring would self-deadlock
/// (`WouldBlock`).
///
/// The cold-read body, torn-final-line tolerance, and out-of-order guard live
/// in `forge_core_eventlog` (parameterised over [`ResearchDomain`]); this fn is
/// just the lock acquire + delegate.
///
/// # Errors
///
/// Returns [`ResearchProjectionError::Lock`] if the lock cannot be acquired;
/// [`ResearchProjectionError::Read`] if the log file cannot be read (other than
/// `NotFound`, which yields an empty projection); [`ResearchProjectionError::Parse`]
/// if a well-formed JSON line fails to deserialize as a [`ResearchEvent`].
pub fn project(root: impl AsRef<Path>) -> ProjectionResult {
    let root = root.as_ref();
    let _lock = forge_core_eventlog::EventLogLock::acquire::<ResearchProjectionDiagnostic>(
        root,
        RESEARCH_LOCK_RELATIVE_PATH,
    )?;
    project_locked::<ResearchDomain>(root, RESEARCH_LOG_RELATIVE_PATH)
}

#[cfg(test)]
mod tests {
    use super::*;
    use forge_core_contracts::{ResearchSourceKind, SourceId};

    fn sample_source(id: &str) -> ResearchSource {
        ResearchSource {
            id: SourceId(id.into()),
            kind: ResearchSourceKind::Paper,
            title: "A canonical source".into(),
            locator: "https://example.org/source".into(),
            fetched_at: 1_700_000_000,
            content_hash: Some("sha256:abc".into()),
            harvested_by: "agent.1".into(),
            trace_ref: Some("run.1".into()),
        }
    }

    fn added(seq: u64, id: &str) -> ResearchEvent {
        ResearchEvent::SourceAdded {
            sequence: seq,
            at_unix: 1_700_000_000 + seq,
            source: sample_source(id),
        }
    }

    fn retired(seq: u64, id: &str) -> ResearchEvent {
        ResearchEvent::SourceRetired {
            sequence: seq,
            at_unix: 1_700_000_000 + seq,
            before: sample_source(id),
        }
    }

    #[test]
    fn replay_empty_yields_empty_projection() {
        let projection: ResearchProjection = replay::<ResearchDomain>(std::iter::empty());
        assert_eq!(projection.sequence, 0);
        assert!(projection.is_empty());
        assert!(projection.diagnostics.is_empty());
    }

    #[test]
    fn replay_source_added_inserts_and_advances_sequence() {
        let events = [added(1, "s.one")];
        let projection = replay::<ResearchDomain>(events);
        assert_eq!(projection.sequence, 1);
        assert_eq!(projection.len(), 1);
        assert!(projection.sources.contains_key("s.one"));
        assert!(projection.superseded.is_empty());
    }

    #[test]
    fn replay_retired_removes_source_and_marks_superseded() {
        let events = [added(1, "s.one"), retired(2, "s.one")];
        let projection = replay::<ResearchDomain>(events);
        assert!(projection.sources.is_empty());
        assert!(projection.superseded.contains("s.one"));
        assert_eq!(projection.sequence, 2);
    }

    #[test]
    fn replay_ignores_out_of_order_event_without_regressing() {
        let first = added(5, "s.five");
        let mut projection = replay::<ResearchDomain>([first]);
        projection.apply_event(&added(2, "s.two"));
        assert_eq!(projection.sequence, 5, "sequence must not regress");
        assert!(
            !projection.sources.contains_key("s.two"),
            "stale event must not insert"
        );
        assert!(projection
            .diagnostics
            .iter()
            .any(|d| d.code == "out_of_order_event_ignored"));
    }

    #[test]
    fn replay_last_event_wins_on_redundant_add() {
        let mut first = sample_source("s.dup");
        first.title = "first".into();
        let mut second = sample_source("s.dup");
        second.title = "second".into();
        let events = [
            ResearchEvent::SourceAdded {
                sequence: 1,
                at_unix: 1,
                source: first,
            },
            ResearchEvent::SourceAdded {
                sequence: 2,
                at_unix: 2,
                source: second,
            },
        ];
        let projection = replay::<ResearchDomain>(events);
        assert_eq!(projection.sources["s.dup"].title, "second");
    }

    #[test]
    fn event_accessors_return_sequence_and_at_unix() {
        let event = added(7, "s.seven");
        assert_eq!(event.sequence(), 7);
        assert_eq!(event.at_unix(), 1_700_000_007);
    }

    #[test]
    fn next_sequence_starts_at_one_and_saturates() {
        let empty = ResearchProjection::default();
        assert_eq!(next_sequence::<ResearchDomain>(&empty), 1);
        let high = ResearchProjection {
            sequence: u64::MAX,
            ..ResearchProjection::default()
        };
        assert_eq!(
            next_sequence::<ResearchDomain>(&high),
            u64::MAX,
            "saturating add must not overflow"
        );
    }

    // --- project(): the cold-read-on-disk path. Its in-memory `replay` body is
    // covered above; these tests exercise the file-reading half via a real
    // state root (the documented three error/soft-diagnostic paths).

    /// Hand-rolled temp dir (repo convention: no `tempfile` workspace dep).
    fn temp_root(label: &str) -> std::path::PathBuf {
        let pid = std::process::id();
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| d.as_nanos());
        let path = std::env::temp_dir().join(format!("forge-research-lib-{label}-{pid}-{nanos}"));
        std::fs::create_dir_all(&path).expect("create temp root");
        path
    }

    /// Helper: serialize a `SourceAdded` event to one JSONL line.
    fn added_line(seq: u64, id: &str) -> String {
        serde_json::to_string(&added(seq, id)).expect("serialize event")
    }

    /// A torn (truncated / invalid-JSON) FINAL line is a soft diagnostic: the
    /// projection applies the good records above it and records a warning, but
    /// the read is still `Ok`. This mirrors the memory PEP's tolerance and is
    /// the documented contract of `project` / `project_locked`.
    #[test]
    fn project_tolerates_torn_final_line_on_disk() {
        let root = temp_root("torn-final");
        std::fs::create_dir_all(root.join("research")).expect("mkdir");
        // Two good lines, then a truncated JSON fragment.
        let log = format!(
            "{}\n{}\n{{\"SourceAdded\":{{\"sequence\":3,\"at_uni",
            added_line(1, "s.one"),
            added_line(2, "s.two"),
        );
        std::fs::write(root.join(RESEARCH_LOG_RELATIVE_PATH), log).expect("write log");

        let projection = project(&root).expect("torn tail is not a hard error");
        assert_eq!(projection.sequence, 2, "good lines before the tear applied");
        assert!(projection.sources.contains_key("s.one"));
        assert!(projection.sources.contains_key("s.two"));
        assert!(
            !projection.diagnostics.is_empty(),
            "a torn final line must emit at least one diagnostic"
        );
    }

    /// Schema drift — a line that is valid JSON but does not deserialize as a
    /// `ResearchEvent` — is a HARD `Parse` error. Distinct from the torn case:
    /// here the bytes parse as JSON but the shape is wrong, which the design
    /// treats as unrecoverable corruption.
    #[test]
    fn project_hard_fails_on_schema_drift_line() {
        let root = temp_root("schema-drift");
        std::fs::create_dir_all(root.join("research")).expect("mkdir");
        let drift = serde_json::to_string(&serde_json::json!({"unrelated": "shape"}))
            .expect("serialize drift");
        std::fs::write(root.join(RESEARCH_LOG_RELATIVE_PATH), drift).expect("write log");

        let result = project(&root);
        let Err(err) = result else {
            panic!("schema drift must be a hard Parse error, got {result:?}");
        };
        // EventLogError::Parse carries the path + 1-based line number.
        assert!(
            matches!(
                err,
                forge_core_eventlog::EventLogError::Parse { line_number: 1, .. }
            ),
            "expected Parse at line 1, got {err:?}"
        );
    }

    /// Out-of-order sequence on disk is a soft diagnostic, not an error: the
    /// stale event is ignored, the watermark does not regress. This pins the
    /// file-reading variant of the guard (the in-memory variant is covered by
    /// `replay_ignores_out_of_order_event_without_regressing`).
    #[test]
    fn project_ignores_out_of_order_event_on_disk_with_diagnostic() {
        let root = temp_root("ooo");
        std::fs::create_dir_all(root.join("research")).expect("mkdir");
        // seq 5 then seq 2: the second is stale and must be ignored.
        let log = format!("{}\n{}\n", added_line(5, "s.five"), added_line(2, "s.two"));
        std::fs::write(root.join(RESEARCH_LOG_RELATIVE_PATH), log).expect("write log");

        let projection = project(&root).expect("out-of-order is not a hard error");
        assert_eq!(projection.sequence, 5, "watermark must not regress");
        assert!(
            projection.sources.contains_key("s.five"),
            "the in-order event applied"
        );
        assert!(
            !projection.sources.contains_key("s.two"),
            "the stale event was ignored"
        );
        assert!(
            !projection.diagnostics.is_empty(),
            "an out-of-order event must emit a diagnostic"
        );
    }

    // --- proptest: the Fowler replay-determinism guarantee ---
    #[cfg(test)]
    mod proptests {
        use super::*;
        use forge_core_contracts::SourceId;
        use proptest::prelude::*;

        fn arb_source_id() -> impl Strategy<Value = String> {
            "[a-z]{1,3}\\.source\\.[0-9]{1,3}"
        }

        fn arb_source(id: String) -> ResearchSource {
            ResearchSource {
                id: SourceId(id),
                kind: ResearchSourceKind::Paper,
                title: "t".into(),
                locator: "https://example.org/x".into(),
                fetched_at: 1,
                content_hash: Some("sha256:0".into()),
                harvested_by: "agent.1".into(),
                trace_ref: Some("run.1".into()),
            }
        }

        fn arb_event(seq: u64, id: String) -> ResearchEvent {
            // Two event shapes, picked by seq % 2 to keep it deterministic.
            match seq % 2 {
                0 => ResearchEvent::SourceAdded {
                    sequence: seq,
                    at_unix: seq,
                    source: arb_source(id),
                },
                _ => ResearchEvent::SourceRetired {
                    sequence: seq,
                    at_unix: seq,
                    before: arb_source(id),
                },
            }
        }

        proptest! {
            /// Replay determinism: the same event stream ⇒ the same projection.
            #[test]
            fn replay_is_deterministic(events in proptest::collection::vec(arb_source_id(), 0..20)) {
                let stream: Vec<ResearchEvent> = events
                    .iter()
                    .enumerate()
                    .map(|(i, id)| arb_event((i as u64) + 1, id.clone()))
                    .collect();
                let first = replay::<ResearchDomain>(stream.iter().cloned());
                let second = replay::<ResearchDomain>(stream.iter().cloned());
                prop_assert_eq!(&first, &second, "replay must be deterministic");
                prop_assert_eq!(first.sequence, stream.len() as u64);
            }

            /// Replay advances sequence monotonically for a monotonic input stream.
            #[test]
            fn replay_advances_sequence_monotonically(events in proptest::collection::vec(arb_source_id(), 1..20)) {
                let stream: Vec<ResearchEvent> = events
                    .iter()
                    .enumerate()
                    .map(|(i, id)| arb_event((i as u64) + 1, id.clone()))
                    .collect();
                let stream_len = stream.len();
                let projection = replay::<ResearchDomain>(stream.into_iter());
                prop_assert_eq!(
                    projection.sequence,
                    u64::try_from(stream_len).unwrap()
                );
            }
        }
    }
}
