//! Declarative macros that collapse the most mechanical event-sourcing
//! triplication.
//!
//! # Why `macro_rules!` (not a proc-macro)
//!
//! A procedural macro would need its own `forge-core-eventlog-derive` crate
//! (compiled as a `proc-macro = true` dylib), adding a build-time dependency
//! and a second compilation unit for every consumer — against the Rust 2024H2 /
//! 2025H1 "reduce proc-macro build cost" direction. A declarative
//! [`macro_rules!`] is hygienic, composable, has zero build-time cost beyond
//! the single crate it already lives in, and is debuggable with
//! `cargo expand`. The trade is expressiveness: `macro_rules!` cannot inspect
//! tokens as deeply, so we only generate what is truly mechanical (the
//! `sequence`/`at_unix` envelope accessors). The fold (`apply`) is intentionally
//! NOT macro-generated — it is domain-specific and clearer written by hand.

/// Generate the [`EventEnvelope`](crate::EventEnvelope) `impl` for a domain's
/// `Event` enum.
///
/// Every copied `Event` enum has the same accessor pair:
///
/// ```ignore
/// impl MemoryEvent {
///     pub fn sequence(&self) -> u64 {
///         match self {
///             Self::Admitted { sequence, .. }
///           | Self::Promoted { sequence, .. }
///           | Self::Forgotten { sequence, .. } => *sequence,
///         }
///     }
///     pub fn at_unix(&self) -> u64 { /* identical shape */ }
/// }
/// ```
///
/// The variants differ per domain but the pattern is invariant: each variant
/// has a `sequence: u64` and `at_unix: u64` field. This macro generates the
/// `impl $enum { fn sequence / fn at_unix }` and the
/// `impl EventEnvelope for $enum` from just the enum name and its variant list.
///
/// # Usage
///
/// ```ignore
/// use forge_core_eventlog::{event_envelope, EventEnvelope};
///
/// #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
/// pub enum CounterEvent {
///     Incremented { sequence: u64, at_unix: u64, delta: i64 },
///     Reset { sequence: u64, at_unix: u64 },
/// }
///
/// event_envelope!(CounterEvent, [Incremented, Reset]);
///
/// let e = CounterEvent::Incremented { sequence: 3, at_unix: 7, delta: 1 };
/// assert_eq!(e.sequence(), 3);
/// assert_eq!(e.at_unix(), 7);
/// ```
///
/// Each variant MUST have `sequence: u64` and `at_unix: u64` fields (the
/// envelope); other fields are ignored via `..`. The macro generates a single
/// `match` arm per variant, OR-ed together.
#[macro_export]
macro_rules! event_envelope {
    ($enum_name:ident, [$($variant:ident),+ $(,)?]) => {
        impl $enum_name {
            /// The per-log monotonic sequence number of this event.
            /// Generated by `forge_core_eventlog::event_envelope!`.
            #[must_use]
            pub fn sequence(&self) -> u64 {
                match self {
                    $(
                        Self::$variant { sequence, .. } => *sequence,
                    )+
                }
            }

            /// `at_unix` timestamp (seconds since epoch).
            /// Generated by `forge_core_eventlog::event_envelope!`.
            #[must_use]
            pub fn at_unix(&self) -> u64 {
                match self {
                    $(
                        Self::$variant { at_unix, .. } => *at_unix,
                    )+
                }
            }
        }

        impl $crate::EventEnvelope for $enum_name {
            fn sequence(&self) -> u64 {
                $enum_name::sequence(self)
            }
            fn at_unix(&self) -> u64 {
                $enum_name::at_unix(self)
            }
        }
    };
}

#[cfg(test)]
mod tests {
    #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
    enum MacroTestEvent {
        Alpha {
            sequence: u64,
            at_unix: u64,
            payload: i64,
        },
        Beta {
            sequence: u64,
            at_unix: u64,
        },
    }

    event_envelope!(MacroTestEvent, [Alpha, Beta]);

    #[test]
    fn macro_generates_envelope_accessors_for_all_variants() {
        let a = MacroTestEvent::Alpha {
            sequence: 11,
            at_unix: 22,
            payload: 5,
        };
        assert_eq!(a.sequence(), 11);
        assert_eq!(a.at_unix(), 22);

        let b = MacroTestEvent::Beta {
            sequence: 33,
            at_unix: 44,
        };
        assert_eq!(b.sequence(), 33);
        assert_eq!(b.at_unix(), 44);
    }
}
