//! `forge-core-governance` — the Policy Enforcement Point (PEP) for the F07
//! multi-principal governance arbitration ledger (ADR-0007).
//!
//! The claim engine (`forge-core-decisions::claim_engine`) is a pure state machine
//! (DD16): on a path-overlap acquire it returns a
//! [`ConflictContract`](forge_core_contracts::ConflictContract) inside the
//! rejection. But the engine touches no filesystem — emitting the conflict to a
//! durable, queryable store is a *separate* concern, and that is what this
//! crate is. It mirrors the F06 split exactly:
//! `forge-core-contracts`/`MemoryContract::can_admit` = the pure PDP;
//! `forge-core-memory` = the PEP that persists the decision under a lock.
//! Here: `GovernancePolicy::can_arbitrate` = the pure PDP;
//! `arbitrate_with_durability` = the PEP.
//!
//! # Architecture (mirrors `forge-core-memory` / ADR-0003)
//!
//! - **Event log** (`governance/conflicts.ndjson`): append-only JSONL. The
//!   source of truth. Never mutated in place ("the dataset only grows" —
//!   rerun.io).
//! - **Projection** ([`ArbitrationProjection`]): the rebuildable read model
//!   (`conflict_id → current ConflictContract`), rebuilt by replaying the log
//!   (Fowler event-sourcing: discard and rebuild the projection).
//! - **Lock**: exclusive OS file lock via
//!   `forge_core_store::acquire_effect_store_lock`, held across
//!   decide-and-write. Reused verbatim — the store crate already implements
//!   TOCTOU-safe locking (CWE-367 — atomicity at the write site).
//!
//! The PEP **never re-evaluates policy** (Cedar/OPA/XACML): a denied decision
//! is a `DeniedByGate` outcome, not an error, and appends nothing.

pub mod arbitrate;
pub mod error;
pub mod escalate;
pub mod record;

use std::collections::BTreeMap;
use std::path::Path;

use forge_core_contracts::{
    ConflictContract, ConflictResolutionState, PrincipalId, ResolutionDecision, StableId,
};
use forge_core_eventlog::{event_envelope, EventSourced};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

// Re-export the generic event-log mechanics under the governance crate's public
// paths so the public API stays stable. These are the generic versions
// parameterised over [`GovernanceDomain`]'s [`EventSourced`] impl: callers pass
// owned events to `replay`, and `project_locked` takes `(root, log_rel_path)`.
pub use forge_core_eventlog::{next_sequence, now_unix, project_locked, replay};

pub use arbitrate::{arbitrate, arbitrate_with_durability, ArbitrateResult, ArbitrateStatus};
pub use error::{ArbitrateError, ArbitrationProjectionError, EscalateError, RecordError};
pub use escalate::{escalate, escalate_with_durability, EscalateResult, EscalateStatus};
pub use record::{record, record_with_durability, RecordResult, RecordStatus};

/// State-root-relative path of the append-only governance arbitration event log.
pub const GOVERNANCE_LOG_RELATIVE_PATH: &str = "governance/conflicts.ndjson";

/// State-root-relative path of the exclusive lock guarding the governance log.
/// Held across every decide-and-write critical section (CWE-367).
pub const GOVERNANCE_LOCK_RELATIVE_PATH: &str = "locks/governance.conflicts.lock";

/// The append-only event stream that is the source of truth for the arbitration
/// ledger. One JSON object per line in `governance/conflicts.ndjson`. Never
/// mutated in place; the projection ([`ArbitrationProjection`]) is the
/// disposable read model.
///
/// Variants mirror the conflict lifecycle:
/// - [`Detected`](GovernanceEvent::Detected) — a conflict entered the ledger at
///   `Pending` resolution (the carrying [`ConflictContract`] is the full
///   attribution record). Emitted by [`record`].
/// - [`Resolved`](GovernanceEvent::Resolved) — an authorized arbiter moved a
///   `Pending` conflict to `Resolved`. Emitted by [`arbitrate`].
/// - [`Escalated`](GovernanceEvent::Escalated) — an authorized arbiter moved a
///   `Pending` conflict to `Escalated`. Emitted by [`escalate`].
///
/// `Resolved`/`Escalated` are transition events: they reference a `conflict_id`
/// rather than re-stating the whole contract, and the projection folds them
/// into the existing conflict's `resolution` field (last-writer-wins on the
/// resolution axis, under the lock).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields, tag = "kind", rename_all = "snake_case")]
pub enum GovernanceEvent {
    Detected {
        sequence: u64,
        at_unix: u64,
        conflict: ConflictContract,
    },
    Resolved {
        sequence: u64,
        at_unix: u64,
        conflict_id: StableId,
        arbiter: PrincipalId,
        decision: ResolutionDecision,
    },
    Escalated {
        sequence: u64,
        at_unix: u64,
        conflict_id: StableId,
    },
}

// The `sequence()`/`at_unix()` envelope accessors + `EventEnvelope` impl are
// generated by the `event_envelope!` macro from forge-core-eventlog (the most
// mechanical triplication — every variant carries `sequence`/`at_unix`).
event_envelope!(GovernanceEvent, [Detected, Resolved, Escalated]);

/// Severity for a projection diagnostic. Mirrors the memory PEP's
/// `MemoryProjectionSeverity` (and the validate crate's `DiagnosticSeverity`
/// granularity) without importing the validator — this crate stays decoupled.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ArbitrationProjectionSeverity {
    Warning,
    Error,
}

/// A non-fatal observation produced while replaying the log (e.g. a torn final
/// line was skipped, an out-of-order sequence was seen, or a `Resolved`/
/// `Escalated` event targeted a conflict that was never `Detected`). The
/// projection stops at the last valid record rather than erroring, mirroring
/// `ClaimWalProjectionError::RecoveryStopped` as a diagnostic, not a hard fail.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ArbitrationProjectionDiagnostic {
    pub severity: ArbitrationProjectionSeverity,
    /// Stable diagnostic code (e.g. `"torn_final_line_skipped"`).
    pub code: String,
    pub message: String,
}

/// The rebuildable read model: `conflict_id → current ConflictContract`. Rebuilt
/// from scratch by [`replay`]; never the source of truth (the event log is).
/// The conflict's `resolution` is folded forward by `Resolved`/`Escalated`
/// events (last-writer-wins under the lock); every other field is set once at
/// `Detected` and never mutated.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ArbitrationProjection {
    /// The highest sequence number applied so far. The next event written is
    /// `sequence + 1`.
    pub sequence: u64,
    /// `conflict_id.0 → current ConflictContract`. Inserted by `Detected`;
    /// resolution folded forward by `Resolved`/`Escalated`.
    pub conflicts: BTreeMap<String, ConflictContract>,
    /// Non-fatal observations from the last replay.
    pub diagnostics: Vec<ArbitrationProjectionDiagnostic>,
}

impl ArbitrationProjection {
    /// Apply a single event, advancing the projection. Thin wrapper that
    /// delegates to the generic [`forge_core_eventlog::apply_event`] (which owns
    /// the out-of-order guard); the domain fold itself lives in
    /// [`GovernanceDomain`]'s [`EventSourced::apply`] impl. Kept as a method so
    /// existing callers/tests that hold a `&mut ArbitrationProjection` keep
    /// working.
    pub fn apply_event(&mut self, event: &GovernanceEvent) {
        forge_core_eventlog::apply_event::<GovernanceDomain>(self, event);
    }

    /// Number of conflicts in the ledger.
    #[must_use]
    pub fn len(&self) -> usize {
        self.conflicts.len()
    }

    /// Whether the ledger is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.conflicts.is_empty()
    }
}

/// The marker type carrying the governance domain's [`EventSourced`] impl. The
/// generic event-log mechanics (`replay`, `project_locked`, `append_event`,
/// `next_sequence`) are parameterised over this type so they resolve to the
/// governance event/projection/diagnostic types.
pub struct GovernanceDomain;

impl EventSourced for GovernanceDomain {
    type Event = GovernanceEvent;
    type Projection = ArbitrationProjection;
    type Diagnostic = ArbitrationProjectionDiagnostic;

    fn apply(projection: &mut Self::Projection, event: &Self::Event) {
        match event {
            GovernanceEvent::Detected { conflict, .. } => {
                // Last-Detected-wins on a redundant detect (matches the memory
                // PEP's redundant-Admit rule). The conflict_id is deterministic
                // and ordering-independent (claim_engine::build_conflict sorts
                // principals), so a re-emit carries the same id.
                projection
                    .conflicts
                    .insert(conflict.conflict_id.0.clone(), conflict.clone());
            }
            GovernanceEvent::Resolved {
                conflict_id,
                arbiter,
                decision,
                ..
            } => match projection.conflicts.get_mut(&conflict_id.0) {
                Some(conflict) => {
                    conflict.resolution = ConflictResolutionState::Resolved {
                        arbiter: arbiter.clone(),
                        decided_at: event.at_unix(),
                        decision: decision.clone(),
                    };
                }
                None => projection
                    .diagnostics
                    .push(ArbitrationProjectionDiagnostic {
                        severity: ArbitrationProjectionSeverity::Warning,
                        code: "resolution_target_missing".into(),
                        message: format!(
                            "Resolved event targeted unknown conflict {}",
                            conflict_id.0
                        ),
                    }),
            },
            GovernanceEvent::Escalated { conflict_id, .. } => {
                match projection.conflicts.get_mut(&conflict_id.0) {
                    Some(conflict) => {
                        conflict.resolution = ConflictResolutionState::Escalated;
                    }
                    None => projection
                        .diagnostics
                        .push(ArbitrationProjectionDiagnostic {
                            severity: ArbitrationProjectionSeverity::Warning,
                            code: "resolution_target_missing".into(),
                            message: format!(
                                "Escalated event targeted unknown conflict {}",
                                conflict_id.0
                            ),
                        }),
                }
            }
        }
    }

    fn record_diagnostic(projection: &mut Self::Projection, diagnostic: Self::Diagnostic) {
        projection.diagnostics.push(diagnostic);
    }

    fn sequence_of(projection: &Self::Projection) -> u64 {
        projection.sequence
    }

    fn advance_sequence(projection: &mut Self::Projection, new_sequence: u64) {
        projection.sequence = new_sequence;
    }

    fn diagnostic_out_of_order_event_ignored(
        event_seq: u64,
        projection_seq: u64,
    ) -> Self::Diagnostic {
        ArbitrationProjectionDiagnostic {
            severity: ArbitrationProjectionSeverity::Warning,
            code: forge_core_eventlog::CODE_OUT_OF_ORDER_EVENT_IGNORED.into(),
            message: format!(
                "event sequence {event_seq} <= projection sequence {projection_seq}; ignored"
            ),
        }
    }

    fn diagnostic_torn_final_line_skipped(
        line_number: usize,
        source: &serde_json::Error,
    ) -> Self::Diagnostic {
        ArbitrationProjectionDiagnostic {
            severity: ArbitrationProjectionSeverity::Warning,
            code: forge_core_eventlog::CODE_TORN_FINAL_LINE_SKIPPED.into(),
            message: format!("skipped incomplete final line {line_number}: {source}"),
        }
    }
}

/// The status of an [`project`] read. The `Ok` arm always carries the
/// projection (which may itself carry diagnostics); only structural I/O or
/// deserialization failures are `Err`. Now an alias for
/// [`EventLogError<ArbitrationProjectionDiagnostic>`](forge_core_eventlog::EventLogError).
pub type ProjectionResult = Result<ArbitrationProjection, ArbitrationProjectionError>;

/// Read the governance log under the lock and rebuild the projection by replay.
///
/// **Acquires the lock.** Callers already holding the governance lock (the PEP
/// entry points: `record`, `arbitrate`, `escalate`, `list`) must call
/// [`forge_core_eventlog::project_locked`] instead — the store lock is NOT
/// re-entrant, so re-acquiring would self-deadlock (return `WouldBlock`).
///
/// The cold-read body, torn-final-line tolerance, and out-of-order guard live
/// in `forge_core_eventlog` (parameterised over [`GovernanceDomain`]); this fn
/// is just the lock acquire + delegate.
///
/// # Errors
///
/// Returns [`ArbitrationProjectionError::Lock`] if the lock cannot be acquired;
/// [`ArbitrationProjectionError::Read`] if the log file cannot be read (other
/// than `NotFound`, which yields an empty projection);
/// [`ArbitrationProjectionError::Parse`] if a well-formed JSON line fails to
/// deserialize as a [`GovernanceEvent`] (schema drift).
pub fn project(root: impl AsRef<Path>) -> ProjectionResult {
    let root = root.as_ref();
    let _lock = forge_core_eventlog::EventLogLock::acquire::<ArbitrationProjectionDiagnostic>(
        root,
        GOVERNANCE_LOCK_RELATIVE_PATH,
    )?;
    project_locked::<GovernanceDomain>(root, GOVERNANCE_LOG_RELATIVE_PATH)
}

/// List conflicts in the ledger, optionally filtered by resolution state.
///
/// Acquires the lock, rebuilds the projection, and returns the conflicts
/// matching `filter` (or all conflicts if `filter` is `None`). Read-only; no
/// event is appended. This is the query backing
/// `forge-core governance conflicts --status open` (F07.6).
///
/// # Errors
///
/// Returns [`ArbitrationProjectionError`] on lock-acquire or read failure.
pub fn list(root: impl AsRef<Path>, filter: Option<ConflictResolutionState>) -> ProjectionResult {
    let projection = project(root)?;
    let conflicts: Vec<ConflictContract> = if let Some(want) = filter {
        projection
            .conflicts
            .into_values()
            .filter(|c| c.resolution == want)
            .collect()
    } else {
        projection.conflicts.into_values().collect()
    };
    Ok(ArbitrationProjection {
        sequence: projection.sequence,
        conflicts: conflicts
            .into_iter()
            .map(|c| (c.conflict_id.0.clone(), c))
            .collect(),
        diagnostics: projection.diagnostics,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use forge_core_contracts::{ConflictDetectionReason, IntentScope, IntentScopeKind};

    fn sample_conflict(id: &str, principal_a: &str, principal_b: &str) -> ConflictContract {
        ConflictContract {
            conflict_id: StableId(id.into()),
            intent_a: StableId(format!("intent.{principal_a}")),
            intent_b: StableId(format!("intent.{principal_b}")),
            principal_a: PrincipalId(principal_a.into()),
            principal_b: PrincipalId(principal_b.into()),
            contested_scope: IntentScope {
                kind: IntentScopeKind::PathPrefix,
                target: StableId("stories".into()),
            },
            detection_reason: ConflictDetectionReason::PathOverlap,
            detected_at: 1_700_000_000,
            resolution: ConflictResolutionState::Pending,
        }
    }

    fn detected(seq: u64, id: &str) -> GovernanceEvent {
        GovernanceEvent::Detected {
            sequence: seq,
            at_unix: 1_700_000_000 + seq,
            conflict: sample_conflict(id, "principal.alice", "principal.bob"),
        }
    }

    #[test]
    fn replay_empty_yields_empty_projection() {
        let projection: ArbitrationProjection = replay::<GovernanceDomain>(std::iter::empty());
        assert_eq!(projection.sequence, 0);
        assert!(projection.is_empty());
        assert!(projection.diagnostics.is_empty());
    }

    #[test]
    fn replay_detected_inserts_conflict_and_advances_sequence() {
        let events = [detected(1, "conflict.1")];
        let projection = replay::<GovernanceDomain>(events);
        assert_eq!(projection.sequence, 1);
        assert_eq!(projection.len(), 1);
        assert!(projection.conflicts.contains_key("conflict.1"));
        assert!(projection.diagnostics.is_empty());
    }

    #[test]
    fn replay_resolved_transitions_resolution() {
        let events = [
            detected(1, "conflict.1"),
            GovernanceEvent::Resolved {
                sequence: 2,
                at_unix: 1_700_000_002,
                conflict_id: StableId("conflict.1".into()),
                arbiter: PrincipalId("principal.daniel".into()),
                decision: ResolutionDecision::AwardedTo(PrincipalId("principal.alice".into())),
            },
        ];
        let projection = replay::<GovernanceDomain>(events);
        let conflict = &projection.conflicts["conflict.1"];
        assert!(matches!(
            conflict.resolution,
            ConflictResolutionState::Resolved { .. }
        ));
        assert_eq!(projection.sequence, 2);
    }

    #[test]
    fn replay_escalated_transitions_resolution() {
        let events = [
            detected(1, "conflict.1"),
            GovernanceEvent::Escalated {
                sequence: 2,
                at_unix: 1_700_000_002,
                conflict_id: StableId("conflict.1".into()),
            },
        ];
        let projection = replay::<GovernanceDomain>(events);
        let conflict = &projection.conflicts["conflict.1"];
        assert_eq!(conflict.resolution, ConflictResolutionState::Escalated);
        assert_eq!(projection.sequence, 2);
    }

    #[test]
    fn replay_resolved_unknown_conflict_emits_diagnostic_without_error() {
        let events = [GovernanceEvent::Resolved {
            sequence: 1,
            at_unix: 1,
            conflict_id: StableId("conflict.missing".into()),
            arbiter: PrincipalId("principal.daniel".into()),
            decision: ResolutionDecision::BothReleased,
        }];
        let projection = replay::<GovernanceDomain>(events);
        assert!(projection.conflicts.is_empty());
        assert_eq!(projection.diagnostics.len(), 1);
        assert_eq!(projection.diagnostics[0].code, "resolution_target_missing");
        assert_eq!(projection.sequence, 1);
    }

    #[test]
    fn replay_ignores_out_of_order_event_without_regressing() {
        let first = detected(5, "conflict.five");
        let mut projection = replay::<GovernanceDomain>([first]);
        projection.apply_event(&detected(2, "conflict.two"));
        assert_eq!(projection.sequence, 5, "sequence must not regress");
        assert!(
            !projection.conflicts.contains_key("conflict.two"),
            "stale event must not insert"
        );
        assert!(projection
            .diagnostics
            .iter()
            .any(|d| d.code == "out_of_order_event_ignored"));
    }

    #[test]
    fn event_accessors_return_sequence_and_at_unix() {
        let event = detected(7, "conflict.seven");
        assert_eq!(event.sequence(), 7);
        assert_eq!(event.at_unix(), 1_700_000_007);
    }

    #[test]
    fn next_sequence_starts_at_one_and_saturates() {
        let empty = ArbitrationProjection::default();
        assert_eq!(next_sequence::<GovernanceDomain>(&empty), 1);
        let high = ArbitrationProjection {
            sequence: u64::MAX,
            ..ArbitrationProjection::default()
        };
        assert_eq!(
            next_sequence::<GovernanceDomain>(&high),
            u64::MAX,
            "saturating add must not overflow"
        );
    }

    // --- proptest: the Fowler replay-determinism guarantee ---
    #[cfg(test)]
    mod proptests {
        use super::*;
        use proptest::prelude::*;

        fn arb_conflict_id() -> impl Strategy<Value = String> {
            "conflict\\.[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,5}"
        }

        fn arb_event(seq: u64, id: String) -> GovernanceEvent {
            match seq % 3 {
                0 => GovernanceEvent::Detected {
                    sequence: seq,
                    at_unix: seq,
                    conflict: ConflictContract {
                        conflict_id: StableId(id),
                        intent_a: StableId("intent.a".into()),
                        intent_b: StableId("intent.b".into()),
                        principal_a: PrincipalId("principal.a".into()),
                        principal_b: PrincipalId("principal.b".into()),
                        contested_scope: IntentScope {
                            kind: IntentScopeKind::PathPrefix,
                            target: StableId("t".into()),
                        },
                        detection_reason: ConflictDetectionReason::PathOverlap,
                        detected_at: seq,
                        resolution: ConflictResolutionState::Pending,
                    },
                },
                1 => GovernanceEvent::Resolved {
                    sequence: seq,
                    at_unix: seq,
                    conflict_id: StableId(id),
                    arbiter: PrincipalId("principal.daniel".into()),
                    decision: ResolutionDecision::BothReleased,
                },
                _ => GovernanceEvent::Escalated {
                    sequence: seq,
                    at_unix: seq,
                    conflict_id: StableId(id),
                },
            }
        }

        proptest! {
            /// Replay determinism: the same event stream ⇒ the same projection.
            #[test]
            fn replay_is_deterministic(events in proptest::collection::vec(arb_conflict_id(), 0..20)) {
                let stream: Vec<GovernanceEvent> = events
                    .iter()
                    .enumerate()
                    .map(|(i, id)| arb_event((i as u64) + 1, id.clone()))
                    .collect();
                let first = replay::<GovernanceDomain>(stream.iter().cloned());
                let second = replay::<GovernanceDomain>(stream.iter().cloned());
                prop_assert_eq!(&first, &second, "replay must be deterministic");
                prop_assert_eq!(first.sequence, stream.len() as u64);
            }

            /// Replay advances sequence monotonically for a monotonic input
            /// stream. Diagnostics are NOT asserted empty here: a Resolved/
            /// Escalated of a never-Detected id correctly emits
            /// `resolution_target_missing`.
            #[test]
            fn replay_advances_sequence_monotonically(events in proptest::collection::vec(arb_conflict_id(), 1..20)) {
                let stream: Vec<GovernanceEvent> = events
                    .iter()
                    .enumerate()
                    .map(|(i, id)| arb_event((i as u64) + 1, id.clone()))
                    .collect();
                let stream_len = stream.len();
                let projection = replay::<GovernanceDomain>(stream.into_iter());
                prop_assert_eq!(projection.sequence, u64::try_from(stream_len).unwrap());
            }
        }
    }
}
