#!/usr/bin/env python3
"""Generate the Forge workspace layout from Cargo metadata.

The generated document is intentionally small and agent-readable. It prevents
README/AGENTS drift by making `cargo metadata --format-version=1 --no-deps`
the source of truth for workspace members, target kinds, and direct workspace
dependencies.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "generated" / "workspace-layout.md"


def cargo_metadata() -> dict:
    result = subprocess.run(
        ["cargo", "metadata", "--format-version=1", "--no-deps"],
        cwd=ROOT,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(result.returncode)
    return json.loads(result.stdout)


def as_repo_path(path: str, workspace_root: Path) -> str:
    return Path(path).parent.relative_to(workspace_root).as_posix()


def target_kinds(package: dict) -> str:
    kinds: list[str] = []
    for target in package.get("targets", []):
        for kind in target.get("kind", []):
            if kind not in kinds:
                kinds.append(kind)
    return ", ".join(kinds) if kinds else "-"


def workspace_dependencies(package: dict, workspace_names: set[str]) -> str:
    deps: list[str] = []
    for dep in package.get("dependencies", []):
        dep_name = dep.get("rename") or dep.get("name")
        if dep_name in workspace_names and dep_name not in deps:
            deps.append(dep_name)
    return ", ".join(deps) if deps else "-"


def render(metadata: dict) -> str:
    workspace_root = Path(metadata["workspace_root"])
    packages = {package["id"]: package for package in metadata["packages"]}
    members = [packages[member] for member in metadata["workspace_members"]]
    workspace_names = {package["name"] for package in members}

    lines = [
        "# Workspace Layout",
        "",
        "<!-- Generated by scripts/generate-workspace-layout.py; do not edit by hand. -->",
        "",
        "Workspace root: repository root",
        f"Workspace members: **{len(members)}**",
        "",
        "| Package | Path | Targets | Direct workspace dependencies |",
        "|---|---|---|---|",
    ]
    for package in sorted(members, key=lambda p: as_repo_path(p["manifest_path"], workspace_root)):
        lines.append(
            "| `{name}` | `{path}` | {targets} | {deps} |".format(
                name=package["name"],
                path=as_repo_path(package["manifest_path"], workspace_root),
                targets=target_kinds(package),
                deps=workspace_dependencies(package, workspace_names),
            )
        )
    lines.extend(
        [
            "",
            "## Regeneration",
            "",
            "```bash",
            "python scripts/generate-workspace-layout.py",
            "python scripts/generate-workspace-layout.py --check",
            "```",
            "",
            "The generator consumes `cargo metadata --format-version=1 --no-deps`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output path (default: {DEFAULT_OUTPUT.relative_to(ROOT).as_posix()})",
    )
    args = parser.parse_args()

    output = args.output if args.output.is_absolute() else ROOT / args.output
    content = render(cargo_metadata())
    current = output.read_text(encoding="utf-8") if output.exists() else None

    if args.check:
        if current != content:
            print(f"{output.relative_to(ROOT).as_posix()} is stale; run scripts/generate-workspace-layout.py")
            return 1
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"wrote {output.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
